### ISSUE TITLE
כשעוברים בין מסך לאורך למסך לרוחב באמצע הקראה ההקראה נפסקת וחוזרים למסך הטקסט

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#27]

**Comment by shilo765** [comment]
כרגע סידרתי שלא יהיה אפשר לעבור למצב לאורך במצב השמעץ אם רוצים שיהיה אפשרות צריך להחליף עיצוב ואז לסדר את זה כי כרגע יש בערך 4 שורות של טקסט שם
