### ISSUE TITLE
בתצוגה המשולבת כל ההערות פותחות את הערה מספר 1 של אותו פרק

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#30]
בתצוגה החדשה של השמעת ההקראות יחד עם צפיה בהלכות - יש בעיה עם ההערות.
כל הכפתורים של ההערות בכל פרק מציגים את ההערה הראשונה של אותו הפרק

**Comment by shilo765** [comment]
תוקן בpr הנוכחי
