### ISSUE TITLE
גרסה 4: הכפתורים העליונים נעלמו

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#37]
במקומם מופיע "פניני הלכה" צריך להחזיר אותם הם היו חשובים מאוד. למשל הסימניה היתה שם ואיזה פרק כרגע רואים ועוד.

**Comment by shilo765** [comment]
כן ברור. חלק מהשינוי עיצוב עוד לא מומש סופית פשוט

**Comment by rafraph** [comment]
אני מבין. בסדר גמור, רק שלא נוכל לשחרר גרסה בלי הכפתורים האלו

**Comment by shilo765** [comment]
טופלת שונתה גרפיקה
