### ISSUE TITLE
גרסה 4: במסך הטקסט יש למטה כפתורים שמצביעים כלפי מעלה ומטה והם לא עובדים טוב

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#39]
הם אמורים לגלול עמוד שלם, אבל נעשה שינוי ברוחב של ה-header ושל ה-footer ועכשיו הם מעבירים יותר מעמוד. צריך לסנכרן את זה

**Comment by rafraph** [comment]
ה-footer הגדול גורם לבעיה נוספת. כשמגיעים לסוף הפרק לא רואים את השורה האחרונה

**Comment by shilo765** [comment]
תוקן
