### ISSUE TITLE
גרסה 4: ביציאה ממצב משולב ההקראה ממשיכה צריך לסגור אותה

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#47]
במצב משולב ההגיון אומר שהמשתמש מסתכל על המסך כדי לראות את הכתב ולכן אם הוא יותא מהמסך הזה הקריאה צריכה להיפסק

**Comment by shilo765** [comment]
איפה נתקלת בזה? נראה שזה עובד

**Comment by shilo765** [comment]
תוקן?
