### ISSUE TITLE
גרסה 4: במצב שמע כשעוברים עם החצים להלכה אחרת צריך שרשימת ההלכות תיגלל אוטומטית להלכה המושמעת

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#49]
הכוונה היא שאם יש למשל 20 הלכות ובמסך נכנסת רשימה של ה7 הראשונות אז כשיורדים עם החצים להלכה 9 והלאה גלילת רשימת ההלכות צריכה להיות אוטומטית

**Comment by shilo765** [comment]
תוקו
