### ISSUE TITLE
גרסה 4: החיפוש לא עובד

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#50]
אם אני מבין נכון, כדי לחפש צריך לכתוב טקסט ואז ללחוץ על הזכוכית מגדלת. כשאני לוחץ המסך נהיה שחור וחוזר לי למסך הראשי.
בנוסף לחיצה על הזכוכית מגדלת כשאין טקסט אמורה להיות DISABLED

**Comment by shilo765** [comment]
בגלל שהיתה לך גרסא קודמת מזה ונשארו ספרים אז אתה קודם כל צריך לאפשר גישה לאפליקציה(תעשה את זה ידנית)

**Comment by shilo765** [comment]
זה מחפש בכל הספרים כולל באנגלית ואין גישה
