### ISSUE TITLE
גרסה 4: במסך ההגדרות גדול הטקסט הנוכחי לא נשמר

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#52]
אם קבעתי גודל טקסט מסוים אני אמור לראות אותו במסך ההגדרות. הגיון פשוט - אם אני רוצה קצת יותר גדול אני צריך שהסמן יראה לי מה ההגרה הנוכחית ואז אני אגדיל קצת ולא אצטרך להעריך כל פעם מחדש מה הגודל הנוכחי שלי

**Comment by shilo765** [comment]
תוקן
