### ISSUE TITLE
גרסה 4: שינוי מהירות גלילה לא עובד טוב

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#56]
יש כרגע 5 מהירויות גלילה. אם לוחצים על מהירות 4 ואז על מהירות 1 ואז שוב על 4 המהירות של 4 לא חוזרת להיות כמו בלחיצה הראשונה אלא הרבה יותר מהר. נראה כאילו החישוב עושה סכום של הערכים או משהו כזה.
צריך שכל ערך תהיה לו מהירות קבועה.
בנוסף מהירות 5 היא לא כל כך מהירה (אם לוחצים עליה רק פעם אחת) ולכן כדאי להוסיף עוד מהירויות. למשל עד 10

**Comment by shilo765** [comment]
תוקן
