### ISSUE TITLE
גרסה 4: גודל הגופן לא נשמר

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#58]
אני יודע שניסית לפתור את הבעיה הזו אבל זה עדיין לא עובד טוב. לפעמים זה שומר על הגודל ולפעמים לא. תנסה לשחק עם זה ולהיכנס להגדרות פעם מהמסך של הטקסט ופעם מהתוכן ופעם מהמסך הראשי וכל פעם תשנה את הגודל ותיראה אם הוא נשמר.
בנוסף גודל הטקסט הקטן ביותר הוא בינוני. כדאי שהקטן ביותר יהיה יותר קטן

**Comment by shilo765** [comment]
תוקן
