### ISSUE TITLE
גרסה 4: החצים שגוללים עמוד לא עובדים טוב

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#59]
משהו השתנה בתפקוד שלהם. 
1. הם גוללים פחות מעמוד
2. נעלמה האנימציה של הגלילה. יש קפיצה ישירה למיקום הבא.
הגלילה עדיין נשארה טובה כמו שהיה לפני הבאג אם משתמשים בכפתורי הווליום. אז פשוט להשתמש באותה פונקציה של כפתורי הווליום עבור החיצים

**Comment by shilo765** [comment]
תוקן
