### ISSUE TITLE
גרסה 4: גלילה אוטומטית

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#60]
אני רואה שהוספת בה מהירויות עד 10. מעולה.
אבל עדיין יש באג שאם אני לוחץ על מהירות 3 ואז שוב על 3 המהירות גוברת. 
כל מספר אמורה להיות לו מהירות קבועה ואם לוחצים על אותו מספר פעמיים לא אמור להיות שינוי.
כמו שכתבתי, נראה כאילו יש לוגיקה של סכום של המהירויות שנלחצו. כאילו לחיצה על 3 פעמיים זה 6 וזה לא טוב

**Comment by shilo765** [comment]
תוקן
