### ISSUE TITLE
גרסה 4: ליקוטים א

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#61]
ראיתי שבפרקים ד, ו, ז הכותרות מוגדרות בצורה לא טובה. הכותרת הראשית קטנה וכותרות הסעיפים גדולות.
זה גורם שבלחיצה על הכפתור שמציג את הסעיפיפ לא מקבלים את רשימת הסעיפים כי הכפתור הזה מסתמך על סוג הכותרת.
תתקן את זה בבקשה ותעבור על כל הפרקים של הספר הזה לראות שאין בעיה בעוד פרקים

**Comment by shilo765** [comment]
תוקן
