### ISSUE TITLE
גרסה 4: בלחיצת BACK מגיעים למסך התוכן פעמיים

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#63]
ממסך הטקסט לחיצת BACK מעבירה למסך התוכן כאשר רשימת הפרקים בספר בו הייתי פתוחה. לחיצה נוספת על BACK מעבירה שוב למסך התוכן רק שכל הספרים סגורים. זה אמור להעביר אותי למסך הראשי של הפאליקציה ולא שוב למסך התוכן

**Comment by shilo765** [comment]
זה סוגר את הספר הנוכחי זה נותן מעבר יותר נוח בין ספרים זה בכוונה
