### ISSUE TITLE
לפעמים ביציאה ממסך השמע השמע ממשיך

### ISSUE THREAD

**Issue by rafraph** [rafraph/PnineyHalacha#66]
עוד לא ברור לי מה בדיוק הסנריו אבל זה קורה

**Comment by rafraph** [comment]
אני חושב שזה קורה אם יוצאים ממסך ההקראה לפני שההקראה מתחילה

**Comment by shilo765** [comment]
כם זה קורה שיוצאים מהר מהשמע לא אמור להיות בשימוש תדיר של האפליקציה ואולי פעם ב. אם יש לך רעיון איך לשנות את זה אשמח שתגיד לי אם לא אפשר לשים את זה בשינויים בעיד
